#!/bin/bash

echo Run trunk based process...
response=$(curl -s -get "http://localhost:8080/git/push")

echo $response

if [[ $response = 'Pipeline is failed' ]]; then
  exit 1
fi
echo Finish trunk based process!